#!/bin/bash
# TDH 2015-04-27
# Messy script for zimbra password expiry email notification.
# Meant to be performed as daily cronjob run as zimbra user. 
# Redirect output to a file to get a 'log file' of sorts.

# Time taken of script;
echo "$SECONDS Started on: $(date)"

# Set some vars:
# First notification in days, then last warning:
FIRST="7"
LAST="3"
# Pass expiry in days
POLICY="4"
# Sent from:
FROM="admin@selected.local"
DISPLAY_NAME="Admin Mail"
# Domain to check, e.g. 'example.com'; leave blank for all
DOMAIN=""
# Recipient who should receive an email with all expired accounts
ADMIN_RECIPIENT="admin@selected.local"

# Sendmail executable
SENDMAIL=$(ionice -c3 find /opt/zimbra/ -type f -iname sendmail)

# Get all users - it should run once only.
USERS=$(/opt/zimbra/bin/zmprov -l gaa)

# Today's date, in seconds:
DATE=$(date +%s)

# Iterate through them in for loop:
for USER in $USERS; do
    # When was the password set?
    OBJECT="(&(objectClass=zimbraAccount)(mail=$USER))"
    ZIMBRA_LDAP_PASSWORD=$(su - zimbra -c "zmlocalconfig -s zimbra_ldap_password | cut -d ' ' -f3")
    LDAP_MASTER_URL=$(su - zimbra -c "zmlocalconfig -s ldap_master_url | cut -d ' ' -f3")
    LDAPSEARCH=$(ionice -c3 find /opt/zimbra/ -type f -iname ldapsearch)
    PASS_SET_DATE=$($LDAPSEARCH -H $LDAP_MASTER_URL -w $ZIMBRA_LDAP_PASSWORD -D uid=zimbra,cn=admins,cn=zimbra -x $OBJECT | grep zimbraPasswordModifiedTime: | cut -d " " -f 2 | cut -c 1-8)

    # Make the date for expiry from now.
    EXPIRES=$(date -d "$PASS_SET_DATE $POLICY days" +%s)

    # Now, how many days until that?
    DEADLINE=$(( (($DATE - $EXPIRES)) / -86400 ))

    # Email to send to victims, ahem - users...
    SUBJECT="$USER - YOUR EMAIL PASSWORD WILL EXPIRE IN $DEADLINE DAYS"
    BODY="
Kepada Yth $USER,

Dengan ini diberitahukan bahwa password Email Anda akan expire dalam $DEADLINE hari. Harap mengganti password Email Anda segera melalui Web Mail:

 - Akses : https://webmail.bankccbi.com

Cara penggantian password Email :

1. Login pada Web Mail sesuai alamat di atas
2. Pilih tab Preferences
3. Pada menu General | Sign in. klik tombol Change Password
4. Isikan password lama, password baru & konfirmasi password baru Anda
5. Klik tombol Change password untuk menggantinya

Password akun Email minimal terdiri dari 8 karakter, dengan kombinasi alphanumerik (huruf besar, huruf kecil, angka) dan simbol (!@#$, dst.).

Jika memiliki Pertanyaan atau Kesulitan Akses New Mail System dapat menghubungi :
IT Helpdesk 24 Jam - 08119946111 (Call & Whatsapp)

Terima Kasih,
ADMIN MAIL


*) This email is automatically sent by the System, please do not Reply

===============================

Dear $USER,

Notice is hereby given that your Email password will expire in $DEADLINE days. Please change your Email password immediately via Web Mail:

 - Access: https://webmail.bankccbi.com

How to change Email password:

1. Login to Web Mail at the above address 
2. Select the Preferences tab 
3. On the General | Sign in menu. click the Change Password button 
4. Fill in your old password, new password & confirm your new password 
5. Click the Change password button to change it

Passwords must be at least 8 characters long, with a combination of alphanumeric (uppercase, lowercase, numbers) and symbols (!@#$, etc.)

If you have questions or difficulties accessing the New Mail System, please contact :
IT Helpdesk 24 Hours - 08119946111 (Call & Whatsapp)

Regards,
ADMIN MAIL
"

    # Send it off depending on days, adding verbose statements for the 'log'
    # First warning
    if [[ "$DEADLINE" -eq "$FIRST" ]]; then
        (
            echo "To: $USER"
            echo "From: $DISPLAY_NAME <$FROM>"
            echo "Subject: $SUBJECT"
            echo ""
            echo "$BODY"
        ) | $SENDMAIL -t
        echo "Reminder email sent to: $USER - $DEADLINE days left"
    # Second
    elif [[ "$DEADLINE" -eq "$LAST" ]]; then
        (
            echo "To: $USER"
            echo "From: $DISPLAY_NAME <$FROM>"
            echo "Subject: $SUBJECT"
            echo ""
            echo "$BODY"
        ) | $SENDMAIL -t
        echo "Reminder email sent to: $USER - $DEADLINE days left"
    # Final
    elif [[ "$DEADLINE" -eq "1" ]]; then
        (
            echo "To: $USER"
            echo "From: $DISPLAY_NAME <$FROM>"
            echo "Subject: $SUBJECT"
            echo ""
            echo "$BODY"
        ) | $SENDMAIL -t
        echo "Last chance for: $USER - $DEADLINE days left"
    else
        echo "Account: $USER reports; $DEADLINE days on Password policy"
    fi
done

echo "-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-"
